config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users, :only => [:show]
  root to: 'pages#home'
  get '/homepage', to: 'pages#homepage'
  patch 'solicitations/:id/validate', to: "solicitations#validate", as: :validate_solicitation
  patch 'solicitations/:id/confirm_project', to: "projects#confirm_project", as: :confirm_project
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :solicitations, only: [ :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:index, :show, :destroy]
  resources :users, only: [:show, :index]
  resources :projects do
    resources :project_pages, only: [:new, :create, :destroy]
    resources :project_features, only: [:new, :create, :destroy]
    resources :solicitations, only: [:new, :create, :index] do
      resources :intermediary_updates, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :comments, only: :create
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :intermediary_update
  belongs_to :user
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :project_features
  has_many :projects, through: :project_features
  validates :name, :description, presence: true
  monetize :amount_cents
end

app/models/intermediary_update.rb
class IntermediaryUpdate < ApplicationRecord
  has_many_attached :documents
  has_many :users, through: :intermediary_updates
  belongs_to :solicitation
  has_many :comments
end

app/models/level.rb
class Level < ApplicationRecord
  #def self.level_1
    #@level = Level.find_by(name: "Level 1")
  #end
  has_many :users
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  after_create :broadcast_notification

  scope :unread, -> { where(read: false)}

  def broadcast_notification
   NotificationChannel.broadcast_to(recipient, ApplicationController.new.render_to_string(partial: 'notifications/notif', locals: {notification: self }) )
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :project
  monetize :amount_cents
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :project_pages
  validates :name, :description, presence: true
  monetize :amount_cents
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :order
  has_many :solicitations
  has_many :project_features
  has_many :features, through: :project_features
  has_many :project_pages
  has_many :pages, through: :project_pages
  has_many :intermediary_updates, through: :solicitations
  belongs_to :user
  belongs_to :level
  validates :name, presence: true
  attribute :status, default: "new"
  validates :deadline, presence: true
  has_many_attached :attachments
  has_many_attached :photos
  has_many_attached :intermediary_attachments
  monetize :price_cents
  validates :status , inclusion: { in: ["new","general_info","page_stage","feature_stage","published","assigned","confirmed","inspection"] }

  before_save :project_level, if: :will_save_change_to_status?

  def project_difficulty
    @difficulty_sum = 0
    unless self.features.empty?
      self.features.each do |feature|
        @difficulty_sum += feature.difficulty
      end
    end
    @difficulty_sum
  end

  def project_level
    sum = self.project_difficulty
    case sum
    when 0..2
      self.level = Level.find_by(name: "Level 1")
    when 3..4
      self.level = Level.find_by(name: "Level 2")
    when 5..7
      self.level = Level.find_by(name: "Level 3")
    when 8..9
      self.level = Level.find_by(name: "Level 4")
    else
      self.level = Level.find_by(name: "Level 5")
    end
  end

  def total_price
    total = 0
    features.each do |feature|
      total+=feature.amount_cents
        end
      pages.each do |page|
        total+=page.amount_cents
        end
    return total
  end

end

app/models/project_feature.rb
class ProjectFeature < ApplicationRecord
  belongs_to :project
  belongs_to :feature
end

app/models/project_page.rb
class ProjectPage < ApplicationRecord
  belongs_to :project
  belongs_to :page
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :solicitation
  validates :score, :comment, presence: true
  validates :score, :inclusion => { :in => 0..5, :message => " should be between 0 to 5" }
end

app/models/solicitation.rb
class Solicitation < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_one :review
  has_many :intermediary_updates
  validates :status, inclusion: {in: ["Pending", "Accepted", "Denied"]}
  validates :user_id, :project_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :solicitations
  has_many :applied_projects, through: :solicitations, source: :project
  has_many :orders
  has_many :projects
  has_many :intermediary_updates, through: :solicitations
  has_many :reviews,through: :solicitations
  has_one_attached :photo
  has_many :notifications, foreign_key: :recipient_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_create :level_1
  belongs_to :level, optional: :true

  def level_1
    level = Level.first
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @project = Project.find(params[:order][:project_id])

    @order = Order.create!(project: @project, amount: @project.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: @project.name,
        amount: @project.price_cents,
        currency: 'eur',
        quantity: 1
      }],
      success_url: order_url(@order),
      cancel_url: order_url(@order)
    )

    @order.update(checkout_session_id: session.id)
    @pages = Page.all
    @features = Feature.all
    @solicitation = @project.solicitations.find_by(status: "Accepted")
    render "projects/show"
  end

  def show
  @order = current_user.orders.find(params[:id])
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @projects = Project.all
  end

  def homepage
    @projects = Project.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @solicitation = Solicitation.find(params[:solicitation_id])
  end

  def create
    @review = Review.new(review_params)
      @solicitation = Solicitation.find(params[:solicitation_id])
    @review.solicitation = @solicitation
    if @review.save
      redirect_to reviews_path, notice: "Congrats, you submitted a review!"
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:solicitation_id, :score, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @level = @user.level
    @project = @user.projects
    @solicitations = @user.solicitations

    url = "https://api.github.com/users/#{@user.github_username}"
    user_serialized = open(url).read
    @github_user = JSON.parse(user_serialized)
  end 


  def index
    @user = User.all
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Konnected - empower each other</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    -->
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo_banner_purple.png", style:"height: 50px;"%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if current_user.student %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My dashboard
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Browse projects", "#", class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Open projects</a>
              <a class="dropdown-item" href="#">Closed projects</a>
            </div>
          </li>
        <% else %>
          <li class= "nav-item btn-group" data-behavior="notifications">
            <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link" id="bell" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="far fa-bell"></i>
              <span class="badge badge-pill badge-light">
                <%= render 'notifications/notif_badge'%>
              </span>
            </a>

            <div class="dropdown-menu inside-page pre-scrollable" id="navbar-notification" data-user-id="<%=current_user.id%>" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
              <% current_user.notifications.reverse.each do |notification| %>
                <%= render 'notifications/notif', notification: notification %>
              <% end %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My projects
            </a>
            <div class="dropdown-menu move-left" aria-labelledby="navbarDropdown">
              <%= link_to "Add new project", new_project_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Open projects</a>
              <a class="dropdown-item" href="#">Pending solicitations</a>
              <a class="dropdown-item" href="#">Closed projects</a>
            </div>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <span class="nav-link" data-toggle="modal" data-target="#exampleModalCenter">Register</span>
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Do you want to continue as a student or a client?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    <div class="row justify-content-center no-gutters">
                      <div class="col-6">
                      <form method="GET" action="/users/sign_up">
                        <input type="hidden" id="custId" name="student" value="true">
                          <button type="submit">
                            <i class="fas fa-graduation-cap fa-7x"></i>
                          </button>
                      </form>
                      </div>
                      <div class="col-4">
                        <form method="GET" action="/users/sign_up">
                        <input type="hidden" id="custId" name="student" value="false" >
                          <button type="submit">
                            <i class="fas fa-building fa-7x"></i>
                          </button>
                       </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </li>
        <% end %>
    </ul>
  </div>
</div>