config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users, :only => [:show]
  root to: 'pages#home'
  get '/homepage', to: 'pages#homepage'
  patch 'solicitations/:id/validate', to: "solicitations#validate", as: :validate_solicitation
  patch 'solicitations/:id/confirm_project', to: "projects#confirm_project", as: :confirm_project
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :solicitations, only: [ :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:index, :show, :destroy]
  resources :users, only: [:show, :index]
  resources :projects do
    resources :project_pages, only: [:new, :create, :destroy]
    resources :project_features, only: [:new, :create, :destroy]
    resources :solicitations, only: [:new, :create, :index] do
      resources :intermediary_updates, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :comments, only: :create
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :order
  has_many :solicitations
  has_many :project_features
  has_many :features, through: :project_features
  has_many :project_pages
  has_many :pages, through: :project_pages
  has_many :intermediary_updates, through: :solicitations
  belongs_to :user
  belongs_to :level
  validates :name, presence: true
  attribute :status, default: "new"
  validates :deadline, presence: true
  has_many_attached :attachments
  has_many_attached :photos
  has_many_attached :intermediary_attachments
  monetize :price_cents
  validates :status , inclusion: { in: ["new","general_info","page_stage","feature_stage","published","assigned","confirmed","inspection"] }

  before_save :project_level, if: :will_save_change_to_status?

  def project_difficulty
    @difficulty_sum = 0
    unless self.features.empty?
      self.features.each do |feature|
        @difficulty_sum += feature.difficulty
      end
    end
    @difficulty_sum
  end

  def project_level
    sum = self.project_difficulty
    case sum
    when 0..2
      self.level = Level.find_by(name: "Level 1")
    when 3..4
      self.level = Level.find_by(name: "Level 2")
    when 5..7
      self.level = Level.find_by(name: "Level 3")
    when 8..9
      self.level = Level.find_by(name: "Level 4")
    else
      self.level = Level.find_by(name: "Level 5")
    end
  end

  def total_price
    total = 0
    features.each do |feature|
      total+=feature.amount_cents
        end
      pages.each do |page|
        total+=page.amount_cents
        end
    return total
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @pages = Page.all
    @features = Feature.all
    @solicitation = @project.solicitations.find_by(status: "Accepted")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.project_level
    @project.save!
    redirect_to project_path(@project), notice: "The first step of your project has been created"
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(params[:project])
  end

  def confirm_project
    @project = Project.find(params[:id])
    @solicitation = @project.solicitations.find_by(status: "Accepted")
    @project.status = "confirmed"
    if @project.save
      redirect_to project_path(@project)
    else
      root_path
    end

  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    @project.price_cents = @project.total_price
    @project.save
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :status, :deadline, :description, :user_id, :level_id, page_ids: [], feature_ids: [], attachments: [], photos: [])
  end
end

app/views/projects/_confirmation_stage.html.erb
<div class="container my-5">
 <div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" href="/projects/<%=@project.id%>/edit">General information</a>
      </li>
      <li class="nav-item">
        <%= link_to "Add pages", project_path(@project, params: { project: { status: "general_info" } }), method: :put, remote: true, class: "nav-link " %>
      </li>
      <li class="nav-item">
        <%= link_to "Add features", project_path(@project, params: { project: { status: "page_stage" } }), method: :put, remote: true, class: "nav-link " %>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="#" tabindex="-1" aria-disabled="true">Confirm</a>
      </li>
    </ul>
  </div>
  <% if @project.order %>
    <div class="row justify-content-around">
      <div class="col-5 m-3">
        <div class="d-flex flex-column align-items-start justify-content-center border border-dark rounded pl-3">
          <h2 class="my-3">Summary of <%= @project.name %></h2>
          <table class="mt-3">
            <tr>
              <th class="first-col">Pages</th>
              <th class="second-col">Price</th>
              <th class="third-col"></th>
            </tr>
              <% @project.project_pages.each do |page| %>
            <tr>
              <td><%= Page.find(page.page_id).name %></td>
              <td>€<%= Page.find(page.page_id).amount_cents/100 %></td>
              <td><%= link_to project_project_page_path(@project, page), method: :delete, remote: true do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
              </td>
            </tr>
              <% end %>
          </table>
            <table class="mt-5">
              <tr>
                <th class="first-col">Features</th>
                <th class="second-col">Price</th>
                <th class="third-col"></th>
              </tr>
                <% @project.project_features.each do |feature| %>
              <tr>
                <td><%= Feature.find(feature.feature_id).name %></td>
                <td>€<%= Feature.find(feature.feature_id).amount_cents/100 %></td>
                <td><%= link_to project_project_feature_path(@project, feature), method: :delete, remote: true do %>
                  <i class="far fa-trash-alt"></i>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </table>
              <!-- <#%= simple_form_for(Order.new, remote: true) do |f| %>
              <#%= f.input :project_id, as: :hidden, input_html: {value: @project.id } %>
              <#%= f.submit class: "btn btn-primary btn-lg btn-block" %>
              <#% end %> -->
          <hr>
        </div>
      </div>
        <div class="col-5 m-3">
          <ul class="list-group">
            <li class="list-group-item list-group-item-dark"> <h3> TOTAL PRICE: <%= @project.total_price / 100 %> euro</h3></li>
            <li class="list-group-item list-group-item-light">
              <button id="pay" class="btn btn-primary">Pay now</button>
                <script src="https://js.stripe.com/v3/"></script>
                <script>
                  const paymentButton = document.getElementById('pay');
                  paymentButton.addEventListener('click', () => {
                    const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
                    stripe.redirectToCheckout({
                      sessionId: '<%= @project.order.checkout_session_id %>'
                    });
                  });
                </script>
              <%= link_to "Pay Later", project_path(@project, params: { project: { status: "published"}}), method: :put, class:"btn btn-outline-primary" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
   <div class="row justify-content-around">
      <div class="col-5 m-3">
        <div class="d-flex flex-column align-items-start justify-content-center border border-dark rounded pl-3">
          <h2 class="my-3">Summary of <%= @project.name %></h2>
            <table class="mt-3">
              <tr>
                <th class="first-col">Pages</th>
                <th class="second-col">Price</th>
                <th class="third-col"></th>
              </tr>
              <% @project.project_pages.each do |page| %>
              <tr>
                <td><%= Page.find(page.page_id).name %></td>
                <td>€<%= Page.find(page.page_id).amount_cents/100 %></td>
                <td><%= link_to project_project_page_path(@project, page), method: :delete, remote: true do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
                </td>
              </tr>
              <% end %>
            </table>
            <table class="mt-5">
              <tr>
                <th class="first-col">Features</th>
                <th class="second-col">Price</th>
                <th class="third-col"></th>
              </tr>
              <% @project.project_features.each do |feature| %>
                <tr>
                  <td><%= Feature.find(feature.feature_id).name %></td>
                  <td>€<%= Feature.find(feature.feature_id).amount_cents/100 %></td>
                  <td><%= link_to project_project_feature_path(@project, feature), method: :delete, remote: true do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
              <%= simple_form_for(Order.new, remote: true) do |f| %>
              <%= f.input :project_id, as: :hidden, input_html: {value: @project.id } %>
              <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
              <% end %>
            <hr>
        </div>
      </div>
    <div class="col-5 m-3">
        <ul class="list-group">
          <li class="list-group-item list-group-item-dark bg-light"> <h3 class="text-muted"> TOTAL PRICE: <%= @project.total_price / 100 %> euro</h3></li>
          <li class="list-group-item list-group-item-light">
            <button id="pay" class="btn btn-light text-muted bg-light">Pay now</button>
            <button id="pay" class="btn btn-light text-muted bg-light">Pay later</button>
          </li>
        </ul>
      </div>
    </div>
  <% end %>

app/views/projects/_feature_stage.html.erb
<div class="container my-5">
 <div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" href="/projects/<%=@project.id%>/edit">General information</a>
      </li>
      <li class="nav-item">
        <%= link_to "Add pages", project_path(@project, params: { project: { status: "general_info" } }), method: :put, remote: true, class: "nav-link " %>
      </li>
      <li class="nav-item">
        <%= link_to "Add features", project_path(@project, params: { project: { status: "page_stage" } }), method: :put, remote: true, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Confirm</a>
      </li>
    </ul>
  </div>
  <div class="row row-cols-2 justify-content-md-center m-3">
    <div clas="col-8 mt-4">
      <div class="card border-success mt-4">
        <div class="card-header bg-transparent border-success">
          <h1 class="my-3">SELECT FEATURES</h1>
        </div>
          <div class="card-body text-success">
            <%= simple_form_for(@project) do |f| %>
              <input type="hidden" name="project[status]" value="feature_stage">
              <%= f.association :features, as: :check_boxes %>
              <div class="card-footer bg-transparent border-success">
                <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
              </div>
            <% end %>
<!-- Code necessary for the javascript insert_pages -->
            <% @features.each do |feature| %>
              <div id="<%=feature.id%>" class="d-none" data-name="<%= feature.name %>">
                <%= feature.amount_cents %>
              </div>
            <%end%>
<!-- // -->
          </div>
        </div>
      </div>
    <div class="col-4 mt-4">
      <div>
        <ul class="list-group">
          <li class="list-group-item list-group-item-primary w-100"> SHOPPING CART </li>
          <li class="list-group-item list-group-item-dark"> Pricing pages </li>
          <li class="list-group-item list-group-item-light">
            <% @project_pages = @project.pages %>
              <% @project_pages.each do |page| %>
              <div> <%= page.name %> - <%= page.amount_cents/100 %> euro </div>
            <% end %>
          </li>
          <li class="list-group-item list-group-item-dark"> Pricing features </li>
          <li class="list-group-item list-group-item-light" id="feature-list"></li>
          <li class="list-group-item list-group-item-success w-100">
            <h3>Total cost: </h3><div class="d-flex"><h2 id="total" data-total="<%= @project.total_price / 100 %>"><%= @project.total_price / 100%> </h2> EURO </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/projects/_page_stage.html.erb
<div class="container my-5">
 <div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" href="/projects/<%=@project.id%>/edit">General information</a>
      </li>
      <li class="nav-item">
        <%= link_to "Add pages", project_path(@project, params: { project: { status: "general_info" } }), method: :put, remote: true, class: "nav-link " %>
      </li>
      <li class="nav-item">
        <%= link_to "Add features", project_path(@project, params: { project: { status: "page_stage" } }), method: :put, remote: true, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Confirm</a>
      </li>
    </ul>
  </div>
  <div class="row row-cols-2 justify-content-md-center m-3">
    <div clas="col-8 mt-4">
      <div class="card border-success mt-4">
        <div class="card-header bg-transparent border-success">
          <h1 class="my-3">SELECT PAGES</h1>
        </div>
          <div class="card-body text-success">
            <%= simple_form_for(@project) do |f| %>
              <input type="hidden" name="project[status]" value="page_stage">
              <%= f.association :pages, as: :check_boxes %>
              <div class="card-footer bg-transparent border-success">
                <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
              </div>
            <% end %>
<!-- Code necessary for the javascript insert_pages -->
            <% @pages.each do |page| %>
              <div id="<%=page.id%>" class="d-none" data-name="<%= page.name %>">
                <%= page.amount_cents %>
              </div>
            <%end%>
<!-- // -->
          </div>
        </div>
      </div>
    <div class="col-4 mt-4">
      <div>
        <ul class="list-group" >
          <li class="list-group-item list-group-item-primary w-100"> SHOPPING CART </li>
          <li class="list-group-item list-group-item-dark"> Pricing pages </li>
          <li class="list-group-item list-group-item-light" id="cart2"></li>
          <li class="list-group-item list-group-item-success w-100">
           <h3> Total cost: </h3><div class="d-flex"><h2 id="total" data-total="<%= @project.total_price / 100 %>"><%= @project.total_price / 100%> </h2> EURO </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/projects/_student_logged_in.html.erb
<!-- Actual project show page -->
    <div class="container">
    <h1 class="mt-3">Project details:</h1>
      <div class="row">
        <div class="col-sm-12 col-lg-8 bg-white my-3 p-3">
        <h3 class="underlined"><%=@project.name %></h3>
        <h5 class="mt-3"><%=@project.level.definition %></h5>
        <% if ((Time.now - @project.created_at)/3600).round < 24  %>
          <p class="time_update">Posted <%= ((Time.now - @project.created_at)/3600).round%><%= ' hour (s)'.pluralize(1) %> ago</p>
        <% else %>
          <p class="time_update">Posted <%= ((Time.now - @project.created_at)/3600/24).round%><%= ' day(s)'.pluralize(1) %> ago</p>
        <% end %>
        <h5>Project description:</h5>
        <p><%= @project.description %></p>
          <div class="row rounded my-2 py-3 card-shadow height">
            <div class="col-sm  rounded px-3 small_card">
              Total of x hours
            </div>
            <div class="col-sm  rounded px-3 small_card">
              Project length
            </div>
            <div class="col-sm  rounded px-3 small_card">
             <%= @project.level.name %>
            </div>
          </div>
          <h5>Project features:</h5>
          <div class="flex">
            <% @project.features.each do |features| %>
              <div class="flexbox feature_box"><%=features.name%></div>
            <% end %>
          </div>
          <h5>Project pages:</h5>
          <div class="flex">
            <% @project.pages.each do |page| %>
              <div class="flexbox feature_box"><%=page.name%></div>
            <% end %>
          </div>
          <h5>Skills and Expertise:</h5>
          <p>Add the skills requested for the student here</p>
          <h5>Pictures: </h5>
          <!-- Carousel -->
          <div class="col-10 offset-1 d-flex justify-content-center my-3">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
              <% @project.photos.each_with_index do |photo, index|%>
                <% if index == 0 %>
                  <div class="carousel-item active" data-slide-to="<%= index %>">
                    <%= cl_image_tag photo.key, class: "d-block w-100 rounded"%>
                  </div>
                <% else %>
                  <div class="carousel-item">
                    <%= cl_image_tag photo.key, class: "d-block w-100 rounded"%>
                  </div>
                <% end %>
              <% end %>
              </div>
              <a class="carousel-control-prev primary-color" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        <!-- Carousel end -->
          <h5>Files:</h5>
          <div class="flex my-3">
            <%@project.attachments.each do |attachment| %>
              <div class="d-flex align-items-center justify-content-center flex-column mx-2">
                <%= link_to rails_blob_path(attachment, disposition: "attachment"), target: "_blank" do %>
                <i class="fas fa-file-download fa-2x"></i>
                <% end %>
              <p class="time_update" class="text-center"><%= attachment.filename %></p>
              </div>
            <% end %>
          </div>
          <h5>Similar jobs on Konnected</h5>
          <p>Some projects here</p>
        </div>
      <div class="col-sm-12 col-lg-4">
        <div class="bg-white text-center my-3 p-3">
        <h4 class="text-center">Contact the project owner</h4>
        <hr>
        <h5 class="text-center"><%= @project.user.first_name %> <%=@project.user.last_name%></h5>
        <p class="text-center mt-3">Phone: <%=@project.user.phone_number %> </p>
        <p class="text-center">Email: <%= mail_to @project.user.email, @project.user.email %></p>


        <!--Add if statement here for if the student level is equal to the project level otherwise disable the button-->

        <% if @project.status == "assigned" %>
          <button class="btn btn-secondary text-center" disabled>This project has allready been assigned</button>
        <%elsif @project.status == "confirmed" || @project.status =="inspection" %>
          <button class="btn btn-secondary text-center" disabled>This project is closed</button>
        <%elsif @project.status == "published" && @project.level == current_user.level && !current_user.applied_projects.include?(@project) %>
          <%= link_to "Apply for this project", new_project_solicitation_path(@project), class:"btn btn-primary text-center"%>
        <% elsif @project.status == "assigned" && current_user.id == @project.solicitations.where(status == "Accepted") %>
              <%= link_to "Latest updates", solicitation_path(@solicitation), class:"btn btn-primary text-center"%>
        <% else %>
          <button class="btn btn-secondary" disabled>You can't apply for this project yet</button>
        <% end %>
        </div>
        <div class="bg-white my-3 p-3">
        <h4 class="text-center">About the employer</h4>
        <hr>
        <h5 class="text-center"><%= @project.user.company_name %></h5>
        <p class="text-center">Location: <%=@project.user.address %> </p>
        <p class="text-center">Projects completed: <%=rand(1..20) %> </p>
        <p class="text-center">Member since: <%=@project.user.created_at.strftime("%d of %B, %Y")%> </p>
        <p class="text-center bold">Average rating: <span class="primary-color bold"><%= "★" * rand(2..5).to_i%></span></p>
        <p class="text-center success-color success_box bold width 100%"> VERIFIED </p>
      </div>
    </div>
  </div>

app/views/projects/edit.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="/projects/<%=@project.id%>/edit">General information</a>
        </li>
        <li class="nav-item">
          <%= link_to "Add pages", project_path(@project, params: { project: { status: "general_info" } }), method: :put, remote: true, class: "nav-link " %>
        </li>
        <li class="nav-item">
          <%= link_to "Add features", project_path(@project, params: { project: { status: "page_stage" } }), method: :put, remote: true, class: "nav-link " %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Confirm</a>
        </li>
      </ul>
    </div>
    <div class="p-5">
      <h1 class="my-3">Create a project</h1>
      <%= simple_form_for(@project) do |f| %>
        <input type="hidden" name="project[status]" value="general_info">
        <%= f.input :name, placeholder: "For example: Landing page" %>
        <%= f.input :description, input_html: { id: 'text_form' }, placeholder: "I would like to hire a freelancer to build a website very similar to Airbnb. The website should have the same functionalities as Airbnb's website: a search bar to get results for a given location, search results, search filters, a payment system, a chat section, notifications, a registration section where users choose on which side of the platform they want to be, a way to identify users to guarantee a certain level of security.
        This is the general structure of the website. I will provide more specific information about clients and workers in private. " %>
        <%= f.input :deadline, as: :date, label: "Project Deadline", start_year: Date.today.year  , end_year: Date.today.year + 10,  order: [:day, :month, :year], include_blank: false %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Add pictures here (optional):"%>
        <%= f.input :attachments, as: :file, input_html: { multiple: true }, label: "Add attachments here (optional):"%>
        <%= f.submit "Update", class: "btn btn-primary my-3"%>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <ul>
  <% @projects.each do |project| %>
    <li><%= project.name %></li>
    <li> Amount: <%= humanized_money_with_symbol(project.price) %></li>
  <% end %>
  </ul>
</div>

app/views/projects/show.html.erb
<!-- In order to go through the different page of the project creation -->
<% @status = @project.status %>
<% case @status %>
<% when "general_info"%>
  <%= render "projects/page_stage" %>
<% when "page_stage"%>
  <%= render "projects/feature_stage" %>
<% when "feature_stage"%>
  <%= render "projects/confirmation_stage" %>
<% else %>
  <% if current_user.student %>
    <%= render "student_logged_in"%>
  <%else %>
      <div class="container">
      <h1 class="mt-3">Project details:</h1>
        <div class="row">
          <div class="col-sm-12 col-lg-8 bg-white my-3 p-3 shadow">
          <h3 class="underlined"><%=@project.name %></h3>
          <% if ((Time.now - @project.created_at)/3600).round < 24  %>
            <p class="time_update">Posted <%= ((Time.now - @project.created_at)/3600).round%><%= ' hour (s)'.pluralize(1) %> ago</p>
          <% else %>
            <p class="time_update">Posted <%= ((Time.now - @project.created_at)/3600/24).round%><%= ' day(s)'.pluralize(1) %> ago</p>
          <% end %>
          <h5>Project description:</h5>
          <p><%= @project.description %></p>
          <h5>Project pages:</h5>
            <div class="flex">
            <% @project.pages.each do |page| %>
                <div class="flexbox feature_box"><%=page.name%></div>
            <% end %>
            </div>
          <h5>Project features:</h5>
            <div class="flex">
            <% @project.features.each do |features| %>
              <div class="flexbox feature_box"><%=features.name%></div>
            <% end %>
            </div>
          <h5>Pictures: </h5>
          <!-- Carousel -->
          <div class="col-10 offset-1 d-flex justify-content-center my-3">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
              <% @project.photos.each_with_index do |photo, index|%>
                <% if index == 0 %>
                  <div class="carousel-item active" data-slide-to="<%= index %>">
                    <%= cl_image_tag photo.key, class: "d-block w-100 rounded"%>
                  </div>
                <% else %>
                  <div class="carousel-item">
                    <%= cl_image_tag photo.key, class: "d-block w-100 rounded"%>
                  </div>
                <% end %>
              <% end %>
              </div>
              <a class="carousel-control-prev primary-color" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        <!-- Carousel end -->
          <h5>Files:</h5>
            <div class="flex my-3">
            <%@project.attachments.each do |attachment| %>
              <div class="d-flex align-items-center justify-content-center flex-column mx-2">
                <%= link_to rails_blob_path(attachment, disposition: "attachment"), target: "_blank" do %>
                <i class="fas fa-file-download fa-2x"></i>
                <% end %>
                <p class="time_update" class="text-center"><%= attachment.filename %></p>
                </div>
            <% end %>
            </div>
          </div>
          <div class="col-sm-12 col-lg-4">
            <div class="bg-white my-3 p-3 text-center shadow">
            <h4 class="text-center"><%= @project.name %></h4>
            <hr>
          <!--Add if statement here for if the company project is confirmed and add a link to the dasboard-->
            <% if @project.status == "assigned" && current_user.id == @project.user_id && @solicitation %>
              <%= link_to "Latest updates", solicitation_path(@solicitation), class:"btn btn-primary text-center"%>
              <%elsif @project.status == "confirmed" && current_user.id == @project.user_id%>
              <button class="btn btn-secondary text-center" disabled>This project is done</button>
            <%elsif @project.status == "published" && current_user.id == @project.user_id && @project.solicitations.length > 0%>
               <%= link_to "See open solicitations (#{@project.solicitations.length})", project_solicitations_path(@project), class:"btn btn-primary text-center"%>
-           <% else %>
             <button class="btn btn-secondary text-center" disabled>This project doesn't have applications yet</button>
             <%= link_to "Your dashboard", root_path, class:"btn btn-primary text-center"%>
              <% end %>
            </div>
            <div class="bg-white my-3 p-3 shadow">
              <h4 class="text-center">About the student</h4>
              <hr>
              <% if @project.status == "published" %>
                <p class="text-center">You haven't assigned a student yet</p>
              <% elsif @project.status == "assigned" && current_user.id == @project.user_id%>
                <% solicitation = @project.solicitations.where(status:"Accepted")[0] %>
                <p class="text-center"><%= "Assigned developer: #{solicitation.user.first_name} #{solicitation.user.last_name}"%></p>
                <p class="text-center"><%= "Phone number: #{solicitation.user.phone_number}"%></p>
                <p class="text-center"><%= "Email: #{solicitation.user.email}"%></p>
                <p class="text-center"> <%=link_to "See Linkedin profile", "#{@project.user.linkedin_profile}" %></p>
                <% unless solicitation.user.website_1.blank?%>
                  <h5 class="text-center">Personal website:</h5>
                  <p class="text-center"><%= "Personal website: #{solicitation.user.website_1}"%></p>
                <% end %>
                <% number_of_projects = solicitation.user.solicitations.where(status: "Accepted")%>
                <% if number_of_projects.length > 0 %>
                  <p class="text-center"><%= "Projects completed: #{number_of_projects.count}"%></p>
                <% end %>
                <p class="text-center">Member since: <%= solicitation.user.created_at.strftime("%d of %B, %Y")%> </p>
                <p class="text-center bold">Average rating: <span class="primary-color bold">★★★★</span></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end %>
<% end %>