config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users, :only => [:show]
  root to: 'pages#home'
  get '/homepage', to: 'pages#homepage'
  patch 'solicitations/:id/validate', to: "solicitations#validate", as: :validate_solicitation
  patch 'solicitations/:id/confirm_project', to: "projects#confirm_project", as: :confirm_project
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :solicitations, only: [ :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:index, :show, :destroy]
  resources :users, only: [:show, :index]
  resources :projects do
    resources :project_pages, only: [:new, :create, :destroy]
    resources :project_features, only: [:new, :create, :destroy]
    resources :solicitations, only: [:new, :create, :index] do
      resources :intermediary_updates, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :comments, only: :create
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/solicitation.rb
class Solicitation < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_one :review
  has_many :intermediary_updates
  validates :status, inclusion: {in: ["Pending", "Accepted", "Denied"]}
  validates :user_id, :project_id, presence: true
end

app/controllers/solicitations_controller.rb
class SolicitationsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @solicitations = @project.solicitations
  end

  def new
    @project = Project.find(params[:project_id])
    @solicitation = Solicitation.new
  end

  def create
    @project = Project.find(params[:project_id])
    @solicitation = Solicitation.new(solicitation_params)
    @solicitation.user_id = current_user.id
    @solicitation.project_id = @project.id
    if @solicitation.save!
      user = @solicitation.project.user
      Notification.create!(recipient: user, actor: current_user, action: "applied", notifiable: @solicitation)
      redirect_to root_path, notice: "Congrats, you applied!"
    else
      render :new
    end
  end

  def validate
    @solicitation = Solicitation.find(params[:id])
    @status = params[:commit]
    if @status == "Select this dev"
     @solicitation.update!(status: "Accepted")
    end
    @project = @solicitation.project
    @solicitation.save
    @project.solicitations.each do |solicitation|
      if solicitation.status == "Pending"
        solicitation.status = "Denied"
        solicitation.save!
      end
    end
    @project.status = "assigned"
    @project.save
    redirect_to project_path(@project)

  end

  def show
    @solicitation = Solicitation.find(params[:id])
    @project = @solicitation.project
    @intermediary_update = @solicitation.intermediary_updates
    @comment = Comment.new
  end


  private

  def solicitation_params
    params.require(:solicitation).permit(:user_id, :project_id, :comment, :status, :photo)
  end
end

app/views/solicitations/index.html.erb
<div class="container">
  <h2 class="text-center">Applications for: "<%=@project.name%>"</h2>
    <!--test-->
    <div class="solicitation-container row">
    <% @project.solicitations.each do |solicitation| %>
      <div class="solicitation-card col-sm-10 col-md-5 col-lg-4 offset-1">
          <div class="card-container-solicitations">
              <span class="pro"><%= solicitation.user.level.name %></span>
              <% if solicitation.user.photo.attached? %>
                <%= cl_image_tag solicitation.user.photo.key, height: 143, width: 143, crop: :fill, class:"round", alt:"user" %>
              <% else %>
                <img class="round" src="https://randomuser.me/api/portraits/women/79.jpg" alt="user" />
              <% end %>
-              <h3><%= link_to"'#{solicitation.user.first_name} #{solicitation.user.last_name}", user_path(solicitation.user)%></h3>
                <p><%=" #{solicitation.comment} "%></p>
    <!-- The value of the button is important for the change of status, if it
      changes, the validate method in thesolicitation controller needs to be modified accordingly -->
                    <%= simple_form_for(solicitation, url: validate_solicitation_path(solicitation), html: {method: :patch}) do |f| %>
                      <%= f.button :submit, 'Select this dev', value: "Select this dev", class: "btn btn-primary"%>
                    <% end %>
                    <div class="d-flex flex-row justify-content-center mb-0">
                      <p class="p-3 mb-0"> <%=link_to "", "#{solicitation.user.phone_number}", target:"_blank", class: "fas fa-phone fa-2x" %></p>
                      <p class="p-3 mb-0"> <%=link_to "", "#{solicitation.user.linkedin_profile}", target:"_blank", class: "fab fa-linkedin fa-2x" %></p>
                      <p class="p-3 mb-0"> <%=link_to "", "#{solicitation.user.website_1}", target:"_blank", class:"fas fa-desktop fa-2x" %></p>
                      <% if solicitation.user.website_2.blank? %>
                      <%else %>
                        <p class="p-3 mb-0"> <%=link_to "", "#{solicitation.user.website_2}", target:"_blank", class:"fas fa-desktop fa-2x" %></p>
                      <% end %>
                      <% if solicitation.user.website_3.blank? %>
                      <%else %>
                        <p class="p-3 mb-0"> <%=link_to "", "#{solicitation.user.website_3}", target:"_blank",  class:"fas fa-desktop fa-2x" %></p>
                      <% end %>
                    </div>
                    <p >Member since:<%=" #{solicitation.user.created_at.strftime("%d of %B, %Y")} "%></p>
                    <div class="skills">
                      <h6 class="text-white">Skills</h6>
                        <ul>
                          <li>UI / UX</li>
                          <li>Front End Development</li>
                          <li>HTML</li>
                          <li>CSS</li>
                          <li>JavaScript</li>
                          <li>React</li>
                          <li>Node</li>
                        </ul>
                    </div>
                   </div>
        </div>
    <%end %>
  </div>
</div>

app/views/solicitations/new.html.erb
<div class="container">
  <h2>Application to project <%= @project.name %></h2>
  <%= simple_form_for [@project, @solicitation] do |f| %>

    <%= f.input :comment, label:"Why do you want to work on this project?" %>
    <%= f.submit "Apply", class:"btn btn-primary"%>
  <% end %>
</div>

app/views/solicitations/show.html.erb
    <div class="container d-flex flex-column align-items-center my-4">
      <h2>Updates of <%= @project.name %></h2>
      <%= link_to "Project details", project_path(@project) %>
      <% if current_user.student %>
        <%= link_to "Add update", new_project_solicitation_intermediary_update_path(@project, @solicitation, @intermediary_update), class:"btn btn-outline-primary" %>
      <% end %>
    </div>

  <div class="container d-flex flex-column align-items-center">
    <% @new_solicitation_first = @solicitation.intermediary_updates.reverse %>
    <% n = @new_solicitation_first.length %>
    <% @new_solicitation_first.each do |update| %>
      <div class="card w-75 my-3">
        <div class="card-header bg-white text-right">
          <%= "#{update.created_at.day}/#{update.created_at.month}/#{update.created_at.year} at #{update.created_at.hour}:#{update.created_at.min} "%>
        </div>
        <div class="card-body">
          <!-- formula to count the number of intermediary update -->
          <h5 class="card-title">Update <%= n %></h5>
          <% n -= 1 %>
          <p class="card-text">
            <%= update.description %>
          </p>
          <% unless update.url.empty? %>
            <p class="card-text"><%= link_to "Click here to see the update", "#{update.url}", target:"_blank"%></p>
          <% end %>
          <% if update.documents %>
              <% update.documents.each do |document| %>
                <div class="d-flex flex-row mx-2">
                  <%= link_to rails_blob_path(document, disposition: "document"), target: "_blank" do %>
                    <i class="fas fa-file-download fa-2x mr-2"></i>
                  <% end %>
                  <p class="time_update" class="text-center"><%= document.filename %></p>
                  </div>
                <% end %>
          <% end %>
          <% if update.accomplished && current_user.student == false %>
            <%= simple_form_for(@project, url: confirm_project_path(@project), html: {method: :patch}) do |f| %>
              <%= f.button :submit , value: "Confirmed", class: "btn btn-primary my-2"%>
            <% end %>

            <%= link_to "Ask for a control", "#", class:"btn btn-outline-danger"%>
          <% end %>
        </div>
        <div>

          <div class="bg-light" id="comments" data-intermediary-update-id="<%= update.id %>">
          <hr>
            <h5 class="container">Comments</h5>
            <% update.comments.each do |comment| %>
              <%= render 'comments/comment', comment: comment%>
            <%end%>
            </div>
            <%= simple_form_for [@project, @solicitation, update, @comment], remote: true do |f| %>
              <div class="d-flex">
                  <%= f.input :content, label: false, placeholder: "Write your message" %>
                  <button type="submit" class="btn btn-primary"><i class="far fa-paper-plane"></i></button>
              </div>
            <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>

<%#= link_to new_solicitation_review_path(@solicitation) %>